name: Build and Deploy to Azure Blob Storage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  NODE_VERSION: '^22'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
            
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Run linting
      run: npm run lint
      continue-on-error: true
      
    - name: Build application
      run: npm run build
      
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Blob Storage
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --auth-mode login \
            --source ./out \
            --destination ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
            --overwrite

    - name: Configure static website hosting (if needed)
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob service-properties update \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --auth-mode login \
            --static-website \
            --index-document index.html \
            --404-document 404.html 