name: Build and Deploy to Azure Blob Storage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  NODE_VERSION: '^22'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
            
    - name: Install dependencies
      run: npm install --legacy-peer-deps
     
    - name: Run linting
      run: npm run lint
      continue-on-error: true
      
    - name: Build application
      run: npm run build
      
    - name: Verify build output
      run: |
        echo "Checking build output directory..."
        ls -la
        echo "Contents of out directory (if it exists):"
        ls -la out/ || echo "out directory does not exist"
        echo "Current working directory: $(pwd)"
      
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Blob Storage
      run: |
        # Get the storage account name from secrets
        STORAGE_ACCOUNT_NAME="${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
        CONTAINER_NAME='${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}'
        
        # Debug: Check if secrets are set
        echo "Storage Account Name: $STORAGE_ACCOUNT_NAME"
        echo "Container Name: $CONTAINER_NAME"
        
        # Check if secrets are provided
        if [ -z "$STORAGE_ACCOUNT_NAME" ]; then
          echo "Error: AZURE_STORAGE_ACCOUNT_NAME secret is not set"
          exit 1
        fi
        
        if [ -z "$CONTAINER_NAME" ]; then
          echo "Error: AZURE_STORAGE_CONTAINER_NAME secret is not set"
          exit 1
        fi
        
        # Check if out directory exists
        if [ ! -d "./out" ]; then
          echo "Error: Build output directory './out' does not exist"
          echo "Available directories:"
          ls -la
          exit 1
        fi
        
        # Upload the built files to blob storage using storage account key
        az storage blob upload-batch \
          --account-name $STORAGE_ACCOUNT_NAME \
          --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
          --source ./out \
          --destination $CONTAINER_NAME \
          --overwrite